services:
  broker-service:
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - appnet

  frontend-service:
    build:
      context: ../front-end
      dockerfile: front-end.dockerfile
    restart: always
    ports:
      - "8081:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge