version: "3.8"
services:
  broker-service:
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - appnet

  frontend-service:
    build:
      context: ../front-end
      dockerfile: front-end.dockerfile
    restart: always
    ports:
      - "8081:80"
    networks:
      - appnet

  authentication-service:
    build:
      context: ../authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    environment:
      DSN: "host=postgres user=postgres password=password dbname=users port=5432 sslmode=disable TimeZone=UTC connect_timeout=5"
    networks:
      - appnet
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
